INSERT OR IGNORE INTO `exercises` (`name`, `equipment`, `movement_pattern`) VALUES
	('Pull-Up', 'bodyweight', 'vertical_pull'),
	('Chin-Up', 'bodyweight', 'vertical_pull'),
	('Lat Pulldown', 'cable', 'vertical_pull'),
	('Assisted Pull-Up', 'machine', 'vertical_pull'),
	('Bent-Over Row', 'barbell', 'horizontal_pull'),
	('One-Arm Row', 'dumbbell', 'horizontal_pull'),
	('Seated Row', 'cable', 'horizontal_pull'),
	('Chest-Supported Row', 'machine', 'horizontal_pull'),
	('Overhead Press', 'barbell', 'vertical_push'),
	('Shoulder Press', 'dumbbell', 'vertical_push'),
	('Shoulder Press', 'machine', 'vertical_push'),
	('Pike Push-Up', 'bodyweight', 'vertical_push'),
	('Bench Press', 'barbell', 'horizontal_push'),
	('Bench Press', 'dumbbell', 'horizontal_push'),
	('Chest Press', 'machine', 'horizontal_push'),
	('Push-Up', 'bodyweight', 'horizontal_push'),
	('Cable Chest Press', 'cable', 'horizontal_push'),
	('Back Squat', 'barbell', 'squat'),
	('Front Squat', 'barbell', 'squat'),
	('Goblet Squat', 'dumbbell', 'squat'),
	('Leg Press', 'machine', 'squat'),
	('Bodyweight Squat', 'bodyweight', 'squat'),
	('Deadlift', 'barbell', 'hinge'),
	('Romanian Deadlift', 'barbell', 'hinge'),
	('Hip Thrust', 'barbell', 'hinge'),
	('Kettlebell Swing', 'kettlebell', 'hinge'),
	('Back Extension', 'bodyweight', 'hinge'),
	('Farmer''s Carry', 'dumbbell', 'carry'),
	('Suitcase Carry', 'dumbbell', 'carry'),
	('Overhead Carry', 'dumbbell', 'carry'),
	('Front Rack Carry', 'kettlebell', 'carry'),
	('Cable Wood Chop', 'cable', 'rotation'),
	('Russian Twist', 'bodyweight', 'rotation'),
	('Landmine Rotation', 'barbell', 'rotation'),
	('Pallof Press', 'cable', 'anti_rotation'),
	('Bird Dog', 'bodyweight', 'anti_rotation'),
	('Plank Shoulder Tap', 'bodyweight', 'anti_rotation'),
	('Barbell Curl', 'barbell', 'elbow_flexion'),
	('Dumbbell Curl', 'dumbbell', 'elbow_flexion'),
	('Cable Curl', 'cable', 'elbow_flexion'),
	('Preacher Curl', 'machine', 'elbow_flexion'),
	('Triceps Pushdown', 'cable', 'elbow_extension'),
	('Skull Crusher', 'barbell', 'elbow_extension'),
	('Overhead Triceps Extension', 'dumbbell', 'elbow_extension'),
	('Triceps Extension', 'machine', 'elbow_extension'),
	('Leg Curl', 'machine', 'knee_flexion'),
	('Nordic Hamstring Curl', 'bodyweight', 'knee_flexion'),
	('Swiss Ball Leg Curl', 'exercise_ball', 'knee_flexion'),
	('Leg Extension', 'machine', 'knee_extension'),
	('Reverse Nordic Curl', 'bodyweight', 'knee_extension'),
	('Terminal Knee Extension', 'cable', 'knee_extension'),
	('Standing Calf Raise', 'machine', 'calf_raise'),
	('Seated Calf Raise', 'machine', 'calf_raise'),
	('Single-Leg Calf Raise', 'bodyweight', 'calf_raise'),
	('Donkey Calf Raise', 'bodyweight', 'calf_raise'),
	('Lateral Raise', 'dumbbell', 'shoulder_abduction'),
	('Lateral Raise', 'cable', 'shoulder_abduction'),
	('Lateral Raise', 'machine', 'shoulder_abduction');
